<!DOCTYPE html>
<!-- Generated by PHPWord -->
<html>
<head>
<meta charset="UTF-8" />
<title>PHPWord</title>
<meta name="author" content="LENOVO" />
<style>
* {font-family: Arial; font-size: 11pt;}
a.NoteRef {text-decoration: none;}
hr {height: 1px; padding: 0; margin: 1em 0; border: 0; border-top: 1px solid #CCC;}
table {border: 1px solid black; border-spacing: 0px; width : 100%;}
td {border: 1px solid black;}
.Normal {margin-bottom: 8pt;}
.pbody {font-family: 'Times New Roman'; font-size: 12pt;}
.Strong {font-weight: bold;}
.Hyperlink {color: #0563C1; text-decoration: underline ;}
</style>
<style>
                                     body {
                                       background-color: #ffffff;
                                     }
                                    </style></head>
<body>
<p style="text-align: center; margin-bottom: 0pt;"><span style="font-family: 'Times New Roman'; font-weight: bold;">GIỚI THIỆU VỀ TẠP CHÍ KHOA HỌC &amp; CÔNG NGHỆ</span><span style="font-family: 'Times New Roman'; font-weight: bold;"> </span><span style="font-family: 'Times New Roman'; font-weight: bold;">TRƯỜNG ĐẠI HỌC KINH TẾ - KỸ THUẬT CÔNG NGHIỆP</span></p>
<p>&nbsp;</p>
<p style="text-align: justify; margin-top: 3pt; margin-bottom: 3pt;"><span style="font-family: 'Times New Roman'; font-size: 13pt;">Tạp chí Khoa học &amp; Công nghệ Trường Đại học Kinh tế - Kỹ thuật Công nghiệp (Journal of Science &amp; Technology University of Economics - Technology for Industries) là </span><span style="font-family: 'Times New Roman'; font-size: 13pt;">t</span><span style="font-family: 'Times New Roman'; font-size: 13pt;">ạp chí học thuật, có phản biện kín hai chiều với chỉ số xuất bản ISSN 0866-7896</span><span style="font-family: 'Times New Roman'; font-size: 13pt; font-weight: bold;">. </span><span style="font-family: 'Times New Roman'; font-size: 13pt;"> </span><span style="font-family: 'Times New Roman'; font-size: 13pt;">Tạp chí là nơi công bố, đăng tải các công trình nghiên cứu khoa học</span><span style="font-family: 'Times New Roman'; font-size: 13pt;">, các thành tựu khoa học, kỹ thuật mới liên quan tới các lĩnh vực mà nhà trường đào tạo. Năm 2012, được sự ủng hộ và cho phép của Bộ Thông tin và Truyền thông, Ban Tuyên giáo Trung ương, Trường Đại học Kinh tế - Kỹ thuật Công nghiệp đã được cấp giấy phép xuất bản “Tạp chí Khoa học và Công nghệ” số 2476/GP – BTTTT ngày 19 tháng 12 năm 2012 của Bộ trưởng Bộ Thông tin Truyền thông. Ngày 05 tháng 6 năm 2013, Tạp chí được Cục Thông tin Khoa học &amp; Công nghệ quốc gia - Bộ Khoa học và Công nghệ cấp mã số chuẩn quốc tế là ISSN 0866-7896. Ngày 02 tháng 6 năm 2023, Tạp chí được Bộ Thông tin và Truyền thông cấp giấy phép số 193/GP-BTTTT cho loại hình in và điện tử.</span></p>
<p style="text-align: justify; margin-top: 3pt; margin-bottom: 3pt;"><span style="font-family: 'Times New Roman'; font-size: 13pt;">Tạp chí được xuất bản định kỳ</span><span style="font-family: 'Times New Roman'; font-size: 13pt;"> (2 tháng/kỳ)</span><span style="font-family: 'Times New Roman'; font-size: 13pt;">, với </span><span style="font-family: 'Times New Roman'; font-size: 13pt;">một số</span><span style="font-family: 'Times New Roman'; font-size: 13pt;"> lĩnh vực khác nhau bao gồm: Kinh tế, công nghệ thông tin, cơ khí, điện tử, vật liệu, môi trường, tự động hóa, cơ điện tử… và các chủ đề liên quan đến khoa học và công nghệ. </span><span style="font-family: 'Times New Roman'; font-size: 13pt;">Tạp chí khuyến khích: Các công trình nghiên cứu dựa trên việc sử dụng các phương pháp, công nghệ &amp; kỹ thuật mới; các kết quả nghiên cứu có tác động lớn đến các địa phương, quốc gia, quốc tế; các nghiên cứu có tính đặc thù về điều kiện kinh tế xã hội &amp; cơ chế quả</span><span style="font-family: 'Times New Roman'; font-size: 13pt;">n lý</span><span style="font-family: 'Times New Roman'; font-size: 13pt;">.</span></p>
<p style="text-align: justify; margin-top: 3pt; margin-bottom: 3pt;"><span style="font-family: 'Times New Roman'; font-size: 13pt;">Trong những năm qua, Tạp chí đã nhận được nhiều bài báo, công trình khoa học của các Nhà nghiên cứu trong và ngoài nước, trở thành Tạp chí có uy tín và được Hội đồng Chức danh Giáo sư Nhà nước đưa vào danh mục các tạp chí khoa học chuyên ngành được tính điểm công trình khi xét công nhận đạt tiêu chuẩn chức danh Giáo sư, Phó Giáo sư cho các bài báo thuộc liên ngành khối Kinh tế (0,5 điểm), ngành Hoá – Công nghệ Thực phẩm (0,5 điểm) và ngành Cơ khí (0,25 điểm).</span></p>
<p style="text-align: justify; margin-top: 3pt; margin-bottom: 3pt;"><span style="font-family: 'Times New Roman'; font-size: 13pt;">Hiện nay, Tạp chí được phát hành bằng bản in và bản điện tử. Với ấn phẩm điện tử, tạp chí sẽ cung cấp khả năng hiển thị tối đa cho các bài báo đã xuất bản và thực hiện truy cập mở hoàn toàn.</span><span style="font-family: 'Times New Roman'; font-size: 13pt;"> </span><span style="font-family: 'Times New Roman'; font-size: 13pt;">Mọi bản thảo trong phạm vi của tạp chí và tuân thủ Quy định bài viết </span><span style="font-family: 'Times New Roman'; font-size: 13pt;">gửi đăng tạp chí sẽ được đưa vào quy trình phản biện sàng lọc và phản biện kín hai chiều bởi ít nhất một chuyên gia độc lập trong lĩnh vực nghiên cứu của bản thảo.</span></p>
<p style="text-align: justify; margin-top: 3pt; margin-bottom: 3pt;"><span style="font-family: 'Times New Roman'; font-size: 13pt;">Các thông tin cụ thể về tạp chí có thể tìm thấy qua trang điện tử: </span><a href="http://tckhcn-uneti.vn">http://tckhcn-uneti.vn</a></p>
<p style="text-align: justify; margin-top: 3pt; margin-bottom: 3pt;"><span style="font-family: 'Times New Roman'; font-size: 13pt;">Email: </span><a href="mailto:tapchikhcn@uneti.edu.vn">tapchikhcn@uneti.edu.vn</a></p>
<p style="text-align: justify; margin-top: 3pt; margin-bottom: 3pt;"><span style="font-family: 'Times New Roman'; font-size: 13pt;">Điện thoại: 024.36321493</span></p>
<p style="margin-top: 0pt; margin-bottom: 7.5pt;"><span style="font-size: 13pt;">Thể thức xuất bản</span></p>
<p style="margin-top: 0pt; margin-bottom: 7.5pt;"><span style="font-size: 13pt;">- Ngôn ngữ thể hiện: Tiếng Việt và Tiếng Anh.</span></p>
<p style="margin-top: 0pt; margin-bottom: 7.5pt;"><span style="font-size: 13pt;">- Kỳ hạn xuất bản: 2 tháng/kỳ.</span></p>
<p style="margin-top: 0pt; margin-bottom: 7.5pt;"><span style="font-size: 13pt;">- Khuôn khổ: 20,5 cm x 29 cm.</span></p>
<p style="margin-top: 0pt; margin-bottom: 7.5pt;"><span style="font-size: 13pt;">- Số trang: 120 trang.</span></p>
<p style="margin-top: 0pt; margin-bottom: 7.5pt;"><span style="font-size: 13pt;">- Nơi in: Hà Nội.</span></p>
</body>
</html>
